Kong/lua-kong-nginx-module

README.md, lualib/resty/kong/tls.lua, t/002-upstream-tls.t
resty.openssl.x509.store object checks
=> fix(set_upstream_ssl_trusted_store) use correct type for

README.md
=> docs(readme) emphasize that `openresty-patches` are required for this

src/ngx_http_lua_kong_module.c, src/ngx_http_lua_kong_module.h, stream/src/ngx_stream_lua_kong_module.c, stream/src/ngx_stream_lua_kong_module.h
There is a LuaJIT bug that is not yet resolved and it causes issues with function calls on macOS+M1. Apple has decided to
break ABI compatibility with ARM64, and thus here we workaround the issue described here:
https://github.com/LuaJIT/LuaJIT/issues/205
Proper fix is to fix LuaJIT, but as that issue has been open since 2016, I thought it would probably be faster to fix this with couple of forward declarations.
This also needs changes in `resty.core.shdict` and `resty.core.response` to take advantage of these new functions. New functions just take struct in and forward the call on C-side to original functions. The issue arises with macOS+M1 if functions have around 8+ arguments. I will link this issue to fixes to above mentioned files, when I decide what is the best way to go with those. …
=> chore(*) add couple of functions for better macOS+M1 support

src/ngx_http_lua_kong_module.c
I think it is an error in C declaration of ffi_set_upstream_ssl_verify.
There is a redundancy param depth, 
and in lua-resty code, the declaration is 
int ngx_http_lua_kong_ffi_set_upstream_ssl_verify(ngx_http_request_t *r,
int verify);
=> fix(tls) remove depth param in ffi_set_upstream_ssl_verify

lualib/resty/kong/tls.lua
We already have `get_request` in `resty.base` module,
I think we need not to keep own implement code in `tls.lua`.
=> chore(tls) use base.get_request instead of own code

README.md
Add desc for `lua_kong_load_default_var_indexes` in readme.md.
Please modify it and let it more helpful for user, sorry for my English.
see: https://github.com/Kong/lua-kong-nginx-module/pull/34
=> doc(var) load default var indexes

config, lualib/resty/kong/tag.lua, src/ngx_http_lua_kong_common.h, src/ngx_http_lua_kong_module.c, src/ngx_http_lua_kong_tag.c, stream/src/ngx_stream_lua_kong_module.c, stream/src/ngx_stream_lua_kong_module.h, t/007-static-tag.t, t/stream/002-static-tag.t
I noticed that we use some vars as semantic tag in nginx config file, 
such as `$kong_proxy_mode`.
It works well but I don't think it is the proper usage of nginx vars.
So I add a new directive `lua_kong_set_static_tag`, which will store the static string in the module's loc_conf_t,
and we can access the value very fast without the cost of var hash searching.
I also did a simple performance test, get the value for 5000*1000 times by `ngx.var` and `tag.get`,
the result is:
0.21599984169006
0.005000114440918
You can see `tag.get` is extremely faster  than `ngx.var`.
If you have interest in this feature I will improve the code, please give me some suggestions.
=> feat(*) a new static tag feature

README.md, t/007-static-tag.t
Add directive and API description for PR #41.
=> docs(readme): doc for lua_kong_set_static_tag

README.md, lualib/resty/kong/tls.lua, src/ngx_http_lua_kong_ssl.c, t/001-tls.t
This API adds the CA DN list to the underlying SSL structure, which will be sent in the Certificate Request message.
The client then can use this DN information to filter the certs and chooses an appropriate cert issued by a CA in the list.
FTI-4430
=> feat(tls) add new API `tls.set_client_ca_list(ca_list)`

lualib/resty/kong/grpc.lua, lualib/resty/kong/tag.lua, lualib/resty/kong/tls.lua, lualib/resty/kong/var.lua, src/ngx_http_lua_kong_ssl.c
Reason of adding this check: 
Although it's indeed redundent given our phase check. but it gives us extra protection because this a private API from openresty, it doesn't guaranteeded to be unchanged in the future. And also given the severity when it happens, it will likely cause a segfault, instead of a lua vm crach.
=> chore(*): add check of get_request() and the missing ';'

.luacheckrc, lualib/resty/kong/var.lua, t/005-indexed-var-openresty-suites.t
set_uri_args modifies the $args variable without accessing our patched metatable. For it to work properly we can invalidate our index table for the value "args" whenever the function `set_uri_args` is called. This way the next access to ngx.var.args will miss the index and fetch the real value of $args.
fix for https://github.com/Kong/kong/issues/10080
[KAG-410](https://konghq.atlassian.net/browse/KAG-410)
[KAG-410]: https://konghq.atlassian.net/browse/KAG-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(var): patch set_uri_args

stream/src/ngx_stream_lua_kong_module.h
This PR is a follow up of #61, remove the useless declaration.
=> chore(src): remove useless declaration in stream

README.md, config, src/ngx_http_lua_kong_common.h, src/ngx_http_lua_kong_directive.h, src/ngx_http_lua_kong_log_handler.c, src/ngx_http_lua_kong_module.c, src/ngx_http_lua_kong_var_index.c, src/ngx_http_lua_kong_vars.c, t/009-error-log-append.t, t/010-request-id.t, t/stream/001-upstream-tls.t
backport of the request id feature to new release: `0.2.2` (based on 0.2.1, used by kong 2.8), includes:
* https://github.com/Kong/lua-kong-nginx-module/pull/65
* https://github.com/Kong/lua-kong-nginx-module/pull/70
=> [backport -> 0.2.2] feat(src): request id (#65 + #70)

t/001-tls.t, t/003-grpc.t
1. The TLS 1.2 Session Resumption via Session Tickets and Session Identifiers mentioned earlier is outdated in TLS 1.3.
2. Replacing `listen ... http2` by `http2 on` to avoid the deprecation message of grpc tests.
=> tests: fix failing tests

README.md, src/ngx_http_lua_kong_var_index.c, t/006-default_indexed-var.t
See: https://github.com/Kong/kong/pull/11722#discussion_r1354048422
=> feat(var): add three variables that are indexed by default

src/ssl/ngx_lua_kong_ssl.c
Fix a warning that is recently being treated as error on macOS.
```
/private/var/tmp/_bazel_fffonion/1a165933b7da774c4bb1daeeee6ca097/execroot/kong/external/lua-kong-nginx-module/src/ssl/ngx_lua_kong_ssl.c:370:42: error: incompatible function pointer types passing 'X509 *(X509 *)' (aka 'struct x509_st *(struct x509_st *)') to parameter of type 'sk_X509_copyfunc' (aka 'struct x509_st *(*)(const struct x509_st *)') [-Wincompatible-function-pointer-types]
new_chain = sk_X509_deep_copy(chain, ngx_lua_kong_ssl_x509_copy,
^~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/tmp/_bazel_fffonion/1a165933b7da774c4bb1daeeee6ca097/execroot/kong/bazel-out/darwin_arm64-fastbuild/bin/external/openresty/openresty.ext_build_deps/openssl/include/openssl/x509.h:102:156: note: expanded from macro 'sk_X509_deep_copy' …
```
=> fix(ssl): add const to ngx_lua_kong_ssl_x509_copy argument

README.md
Reference the effect [here](https://github.com/Kong/lua-kong-nginx-module/tree/doc/new_get_log_level?tab=readme-ov-file#restykonglogget_log_level).
=> docs: specify `timeout` unit for `resty.kong.log.get_log_level()`

README.md, config, lualib/resty/kong/tls.lua, src/ngx_http_lua_kong_ssl.c, stream/config, stream/src/ngx_stream_lua_kong_module.c, t/001-tls.t, t/stream/003-tls.t
=> feat(ssl): add function to get socket ssl

lualib/resty/kong/peer_conn.lua
this PR is an additional section of #82 that ensures `peer_conn` is used correctly under the http subsystem.
Fix [FTI-5616](https://konghq.atlassian.net/browse/FTI-5616)
[FTI-5616]: https://konghq.atlassian.net/browse/FTI-5616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: declare peer_conn can only be used in the http subsystem

.github/workflows/tests.yml
This was temporary changed in #93  to break circular depedency.
=> chore(ci): revert the kong version back to master

.luacheckrc, lualib/resty/kong/var.lua, t/005-indexed-var-openresty-suites.t
patch the `req.set_header` function to invalidate the relevant `variable_index` entry for the modified header. Specifically, after normalizing the header name, the corresponding `variable_index` entry is set to `nil`. This ensures that subsequent accesses to `ngx.var.http_*` variables will bypass the cached index and fetch the updated header value.
same fix way as: https://github.com/Kong/lua-kong-nginx-module/pull/59
Fix: [KAG-5963](https://konghq.atlassian.net/browse/KAG-5963)
Fix: [FTI-6406](https://konghq.atlassian.net/browse/FTI-6406)
[KAG-5963]: https://konghq.atlassian.net/browse/KAG-5963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FTI-6406]: https://konghq.atlassian.net/browse/FTI-6406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> fix(var): patch set_header

.github/workflows/tests.yml, README.md, lualib/resty/kong/upstream.lua, src/ngx_http_lua_kong_common.h, src/ngx_http_lua_kong_module.c, src/ngx_http_lua_kong_module.h, t/013-upstream.t
Set upstream next enablement of current request to the given string of table
argument . Global setting set by [`proxy_next_upstream`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) will be overwritten.
[AG-186](https://konghq.atlassian.net/browse/AG-186)
[AG-186]: https://konghq.atlassian.net/browse/AG-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: control the proxy_upstream in lua side

.github/workflows/tests.yml
fixing the test kong branch to master which https://github.com/Kong/lua-kong-nginx-module/pull/98 changed.
=> chore: restore github action kong version to master

.github/workflows/tests.yml, .luacheckrc, lualib/resty/kong/var.lua, t/005-indexed-var-openresty-suites.t, t/stream/001-upstream-tls.t
patch the req.set_header function to invalidate the relevant variable_index entry for the modified header. Specifically, after normalizing the header name, the corresponding variable_index entry is set to nil. This ensures that subsequent accesses to ngx.var.http_* variables will bypass the cached index and fetch the updated header value.
same fix way as: https://github.com/Kong/lua-kong-nginx-module/pull/59
Fix: [KAG-5963](https://konghq.atlassian.net/browse/KAG-5963)
Fix: [FTI-6406](https://konghq.atlassian.net/browse/FTI-6406)
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
[KAG-5963]: https://konghq.atlassian.net/browse/KAG-5963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FTI-6406]: …
=> fix(var): patch set_header 

.github/workflows/tests.yml
removed the logic for modifying the lua-messagepack version in the .rockspec file from the CI workflow.
releated to:https://github.com/Kong/kong/pull/14061
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
=> chore(ci): update GitHub Actions workflow to remove rockspec modification step

.github/workflows/tests.yml, .luacheckrc, lualib/resty/kong/var.lua, t/005-indexed-var-openresty-suites.t
patch the `req.set_header` function to invalidate the relevant `variable_index` entry for the modified header. Specifically, after normalizing the header name, the corresponding `variable_index` entry is set to `nil`. This ensures that subsequent accesses to `ngx.var.http_*` variables will bypass the cached index and fetch the updated header value.
same fix way as: https://github.com/Kong/lua-kong-nginx-module/pull/59
Fix: KAG-5963
Fix: FTI-6406
=> fix(var): patch set_header (#97)

src/ngx_http_lua_kong_var_index.c, t/006-default_indexed-var.t
We have identified a ~5% RPS performance regression in the Kong EE PR 11452
Upon further investigation, we found that a big chunk of CPU time is spent on ngx.var variables access.
We add upstream timing variables to the default indexed variables list, allowing efficient access through Kong's FFI interface. These variables track detailed timing information for upstream connections:
* upstream_start_timestamp_us
* upstream_connect_timestamp_us
* upstream_request_timestamp_us
* upstream_header_timestamp_us
* upstream_response_timestamp_us
These microsecond-precision timestamps enable detailed upstream latency analysis and troubleshooting of connection issues.
=> feat(vars): index upstream timing variables for FFI access

.github/workflows/lint.yml, README.md, src/ngx_http_lua_kong_var_index.c, t/006-default_indexed-var.t
The request_time variable was previously indexed by default in the NGINX module. However, this behavior is problematic because request_time is a dynamic value that changes over the request lifecycle. Indexing it causes the first access to cache its value, leading to incorrect results for subsequent accesses.
This issue is particularly impactful in Active Tracing, where request_time is used during the log phase. The cached value can result in inaccurate tracing data. This is because the first access to this variable will cache it and subsequent accesses will use the cached value.
This commit removes request_time from the list of default indexed variables to ensure its value is always retrieved dynamically. Corresponding test cases have been updated to reflect this change.
Fix KAG-6868
=> fix(vars): remove request_time from default indexed variables

README.md, lualib/resty/kong/tls.lua, src/ngx_http_lua_kong_module.h, src/ngx_http_lua_kong_ssl.c, src/ssl/ngx_lua_kong_ssl.h, stream/src/ngx_stream_lua_kong_module.c, stream/src/ngx_stream_lua_kong_module.h
This adds two new Lua functions (and the corresponding C logic) to configure custom SANs validation in nginx:
* `resty.kong.tls.set_upstream_ssl_sans_dnsnames()`
* `resty.kong.tls.set_upstream_ssl_sans_uris()`
Part of KAG-6247.
---
Notes:
* This requires a corresponding nginx patch implementing the additional TLS-name validation logic.
* Testing for this change (and the above nginx patch) is done at the integration level in Kong, see linked PR.
=> feat(tls): add SANs support for both DNS-names and URIs
